org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=2
org.gradle.configureondemand=false
kotlin.incremental=true
kotlin.daemon.enabled=true
kotlin.compiler.execution.strategy=in-process
org.gradle.daemon.performance.disable-logging=true
